/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/page`; params?: Router.UnknownInputParams; } | { pathname: `/api/[[...path]]/route`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback/page`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/lessons/page`; params?: Router.UnknownInputParams; } | { pathname: `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `/practice/page`; params?: Router.UnknownInputParams; } | { pathname: `/pricing/page`; params?: Router.UnknownInputParams; } | { pathname: `/pricing/success/page`; params?: Router.UnknownInputParams; } | { pathname: `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `/progress/page`; params?: Router.UnknownInputParams; } | { pathname: `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `/welcome/page`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lessons/[exam]/page`, params: Router.UnknownInputParams & { exam: string | number; } } | { pathname: `/lessons/[exam]/[section]/[lesson]/page`, params: Router.UnknownInputParams & { exam: string | number;section: string | number;lesson: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/page`; params?: Router.UnknownOutputParams; } | { pathname: `/api/[[...path]]/route`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/callback/page`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/page`; params?: Router.UnknownOutputParams; } | { pathname: `/lessons/page`; params?: Router.UnknownOutputParams; } | { pathname: `/login/page`; params?: Router.UnknownOutputParams; } | { pathname: `/practice/page`; params?: Router.UnknownOutputParams; } | { pathname: `/pricing/page`; params?: Router.UnknownOutputParams; } | { pathname: `/pricing/success/page`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/page`; params?: Router.UnknownOutputParams; } | { pathname: `/progress/page`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome/page`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/lessons/[exam]/page`, params: Router.UnknownOutputParams & { exam: string; } } | { pathname: `/lessons/[exam]/[section]/[lesson]/page`, params: Router.UnknownOutputParams & { exam: string;section: string;lesson: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/page${`?${string}` | `#${string}` | ''}` | `/api/[[...path]]/route${`?${string}` | `#${string}` | ''}` | `/auth/callback/page${`?${string}` | `#${string}` | ''}` | `/dashboard/page${`?${string}` | `#${string}` | ''}` | `/lessons/page${`?${string}` | `#${string}` | ''}` | `/login/page${`?${string}` | `#${string}` | ''}` | `/practice/page${`?${string}` | `#${string}` | ''}` | `/pricing/page${`?${string}` | `#${string}` | ''}` | `/pricing/success/page${`?${string}` | `#${string}` | ''}` | `/profile/page${`?${string}` | `#${string}` | ''}` | `/progress/page${`?${string}` | `#${string}` | ''}` | `/signup/page${`?${string}` | `#${string}` | ''}` | `/welcome/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/page`; params?: Router.UnknownInputParams; } | { pathname: `/api/[[...path]]/route`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback/page`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/page`; params?: Router.UnknownInputParams; } | { pathname: `/lessons/page`; params?: Router.UnknownInputParams; } | { pathname: `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `/practice/page`; params?: Router.UnknownInputParams; } | { pathname: `/pricing/page`; params?: Router.UnknownInputParams; } | { pathname: `/pricing/success/page`; params?: Router.UnknownInputParams; } | { pathname: `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `/progress/page`; params?: Router.UnknownInputParams; } | { pathname: `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `/welcome/page`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/lessons/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | `/lessons/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}/page${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lessons/[exam]/page`, params: Router.UnknownInputParams & { exam: string | number; } } | { pathname: `/lessons/[exam]/[section]/[lesson]/page`, params: Router.UnknownInputParams & { exam: string | number;section: string | number;lesson: string | number; } };
    }
  }
}
